print('字符串的表示')
print(r'\n\b\r')
print(b'this is string')
#print(b'一个字符串')
print('一个字符串'.encode(encoding='utf-8'))
print('字符串的拼接：')
a="aaaa"
b="bbbb"
print(a+b)
print('aaa%s' % b)
print('{},{}'.format(a,b))
print('{a},{b},{c:.2f}'.format(a=a,b=b,c=10))
print('字符串的分割：')
print("hello,code".split(","))
print(",".join(["hello","code"]))
print("查找:")
print("hello code".find('code'))
print("替换:")
print("hello code".replace('code','world'))
